[package]
name = "serenity-utils-derive"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "serenity_utils_derive"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"

[dependencies.syn]
version = "2"
features = ["full"]
